package com.example.demo.controller;

import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import com.example.demo.model.Prescription;
import com.example.demo.service.PrescriptionService;
import com.example.demo.service.NotificationService;

@RestController
@RequestMapping("/prescriptions")
@CrossOrigin(origins = "*")
public class PrescriptionController {

    private final PrescriptionService service;
    private final com.example.demo.repository.UserRepository userRepository;
    private final com.example.demo.repository.DoctorRepository doctorRepository;
    private final com.example.demo.repository.HospitalRepository hospitalRepository;
    private final NotificationService notificationService;

    public PrescriptionController(PrescriptionService service,
            com.example.demo.repository.UserRepository userRepository,
            com.example.demo.repository.DoctorRepository doctorRepository,
            com.example.demo.repository.HospitalRepository hospitalRepository,
            NotificationService notificationService) {
        this.service = service;
        this.userRepository = userRepository;
        this.doctorRepository = doctorRepository;
        this.hospitalRepository = hospitalRepository;
        this.notificationService = notificationService;
    }

    @GetMapping("/my")
    public ResponseEntity<List<Prescription>> getMyPrescriptions(java.security.Principal principal) {
        com.example.demo.model.User user = userRepository.findByUsername(principal.getName())
                .orElseThrow(() -> new RuntimeException("User not found"));
        return ResponseEntity.ok(service.getPatientPrescriptions(user.getId()));
    }

    @GetMapping("/{id}/download")
    public ResponseEntity<byte[]> downloadPrescription(@PathVariable("id") Long id) {
        Prescription prescription = service.getPrescriptionById(id);
        String hospitalName = "CareVita Network";
        if (prescription.getHospitalId() != null) {
            hospitalName = hospitalRepository.findById(prescription.getHospitalId())
                    .map(com.example.demo.model.Hospital::getName)
                    .orElse("CareVita Network");
        }

        StringBuilder content = new StringBuilder();
        content.append("-------------------------------------------\n");
        content.append("           CARE VITA PRESCRIPTION          \n");
        content.append("-------------------------------------------\n");
        content.append("Hospital: ").append(hospitalName).append("\n");
        content.append("Date:     ").append(prescription.getPrescriptionDate().toLocalDate()).append("\n");
        content.append("Rx ID:    #").append(id).append("\n");
        content.append("-------------------------------------------\n\n");
        content.append("PATIENT DETAILS:\n");
        content.append("Name:     ").append(prescription.getPatientName()).append("\n");
        content.append("-------------------------------------------\n\n");
        content.append("MEDICATION:\n");
        content.append("Medicine: ").append(prescription.getMedicine()).append("\n");
        content.append("Dosage:   ").append(prescription.getDosage() != null ? prescription.getDosage() : "As directed")
                .append("\n");
        content.append("Note:     ").append(prescription.getInstructions()).append("\n\n");
        content.append("-------------------------------------------\n");
        content.append("Clinician: ").append(prescription.getDoctorName()).append("\n");
        content.append("-------------------------------------------\n");
        content.append("Generated by CareVita Health System\n");

        return ResponseEntity.ok()
                .header("Content-Disposition", "attachment; filename=Rx_" + id + ".txt")
                .body(content.toString().getBytes());
    }

    @PostMapping("/add")
    public ResponseEntity<Prescription> addPrescription(@RequestBody java.util.Map<String, Object> data,
            java.security.Principal principal) {
        com.example.demo.model.User patient = userRepository.findById(Long.valueOf(data.get("patientId").toString()))
                .orElseThrow(() -> new RuntimeException("Patient not found"));

        com.example.demo.model.User doctorUser = userRepository.findByUsername(principal.getName())
                .orElseThrow(() -> new RuntimeException("Doctor user not found"));

        com.example.demo.model.Doctor doctorProfile = doctorRepository.findByEmail(doctorUser.getEmail())
                .orElseThrow(() -> new RuntimeException("Doctor profile not found"));

        Prescription prescription = new Prescription();
        prescription.setPatient(patient);
        prescription.setDoctor(doctorProfile);
        prescription.setPatientName(patient.getFullName());
        prescription.setDoctorName(doctorProfile.getName());
        prescription.setMedicine(data.get("details").toString());
        prescription.setInstructions("Consultation note: " + data.get("details").toString());
        prescription.setStatus("PENDING_DISPATCH");
        prescription.setHospitalId(doctorProfile.getHospitalId());

        Prescription saved = service.savePrescription(prescription);
        notificationService.createNotification(patient, "Doctor " + doctorProfile.getName()
                + " has issued a new prescription for you. Waiting for pharmacist dispatch.", "PRESCRIPTION");
        return ResponseEntity.ok(saved);
    }

    @GetMapping("/hospital/{hospitalId}/pending")
    public ResponseEntity<List<Prescription>> getPending(@PathVariable("hospitalId") Long hospitalId) {
        return ResponseEntity.ok(service.getPendingDispatchByHospital(hospitalId));
    }

    @PutMapping("/{id}/dispatch")
    public ResponseEntity<Prescription> dispatch(@PathVariable("id") Long id) {
        Prescription dispatched = service.updateStatus(id, "ACTIVE");
        notificationService.createNotification(dispatched.getPatient(),
                "Your prescription #" + id + " has been dispatched by the hospital pharmacy.", "PRESCRIPTION");
        return ResponseEntity.ok(dispatched);
    }

    @GetMapping
    public ResponseEntity<List<Prescription>> getPrescriptions() {
        return ResponseEntity.ok(service.getAllPrescriptions());
    }

    @GetMapping("/{id}")
    public ResponseEntity<Prescription> getPrescriptionById(@PathVariable("id") Long id) {
        return ResponseEntity.ok(service.getPrescriptionById(id));
    }

    @GetMapping("/patient/{patientId}")
    public ResponseEntity<List<Prescription>> getPatientPrescriptions(@PathVariable("patientId") Long patientId) {
        return ResponseEntity.ok(service.getPatientPrescriptions(patientId));
    }

    @GetMapping("/doctor/{doctorId}")
    public ResponseEntity<List<Prescription>> getDoctorPrescriptions(@PathVariable("doctorId") Long doctorId) {
        return ResponseEntity.ok(service.getDoctorPrescriptions(doctorId));
    }

    @GetMapping("/patient/{patientId}/active")
    public ResponseEntity<List<Prescription>> getActivePatientPrescriptions(@PathVariable("patientId") Long patientId) {
        return ResponseEntity.ok(service.getActivePatientPrescriptions(patientId));
    }

    @PutMapping("/{id}")
    public ResponseEntity<Prescription> updatePrescription(@PathVariable("id") Long id,
            @RequestBody Prescription prescription) {
        return ResponseEntity.ok(service.updatePrescription(id, prescription));
    }

    @PatchMapping("/{id}/status")
    public ResponseEntity<Prescription> updateStatus(@PathVariable("id") Long id,
            @RequestParam("status") String status) {
        return ResponseEntity.ok(service.updateStatus(id, status));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deletePrescription(@PathVariable("id") Long id) {
        service.deletePrescription(id);
        return ResponseEntity.noContent().build();
    }
}
